### ISSUE TITLE
Auto typing

### ISSUE THREAD

**Issue by therealOri** [zoony1337/typeracer.com-Typer#1]
Doesn't type automatically for you. It does nothing but find and put you in games.
No winning every time happening anytime soon.

**Comment by zoony1337** [comment]
I think you have misunderstood the usage of this tool. It does type automatically for you — and let you win depending on the timeout you input.
What makes you think it doesn't?

**Comment by therealOri** [comment]
Because after the timeout that I set, Nothing happens. No typing.
I even tried to set the timeout to 0.01 and still nothing and no typing.

**Comment by therealOri** [comment]
An entire game went by and the timer finished and it didn't do a thing. not even 1 word. I even had a 1 second timeout.

**Comment by therealOri** [comment]
After trying again and again, after the 10th try, it started working. (I have no idea why this happened or why it wouldn't work for a bit. every attempt was with the same timeout of "1")
